version: '3.8'

services:
  db:
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_DB: lighttech
      POSTGRES_USER: lighttech
      POSTGRES_PASSWORD: lighttech
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  backend:
    build: .
    networks:
      - app-network
    environment:
      DB_NAME: lighttech
      DB_USER: lighttech
      DB_PASSWORD: lighttech
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "sleep 5 && python manage.py migrate \
                    && python manage.py runserver 0.0.0.0:8000"

networks:
  app-network:
    driver: bridge